`timescale 1ns/1ps
`include "kernel.h.sv"

// ============================================================
//  kernel_top  –  Jacobi eigendecomposition (10×10 complex)
//
//  Fixed-point widths (component, two's-complement signed):
//    A, eigenvalues, eigenvectors : 23 bits  (bits=22, signed=1)
//    max_iter, ite               : 16 bits  (bits=16, signed=0)
//
//  Trig approximation strategy
//  ----------------------------
//  We need cos(θ) and sin(θ) where θ = 0.5·atan(2|a_pq|/(a_pp-a_qq)).
//  To keep the design synthesisable without cordic IP we use a
//  look-up-table based CORDIC-free approximation via a 512-entry
//  sine/cosine ROM that is pre-computed and stored as signed 23-bit
//  fixed-point integers (fraction = 20 bits, i.e. Q3.20).
//
//  Because this is a large iterative algorithm (up to 65535 Jacobi
//  sweeps, each sweep touching a 10×10 matrix) the FSM is structured
//  as a micro-sequencer with the following top-level states:
//
//  IDLE → LATCH → ITER_START → FIND_MAX (nested i/j loop) →
//  CHECK_CONV → CALC_THETA → CALC_PHI → BUILD_U →
//  APPLY_U_LEFT (U†·A) → APPLY_U_RIGHT (·U) →
//  UPDATE_V (V·U) → NEXT_ITER → DONE_ST
// ============================================================

module kernel_top (
    input  wire clk,
    input  wire rst,
    input  wire start,
    output reg  busy,
    output reg  done,

    // in0 = A [10][10] complex, component width 23 (re,im interleaved per element)
    input  wire signed [`DIM_IN0_0*`DIM_IN0_1*2*`ACM_W-1:0] in0,
    // in1 = max_iter scalar 16-bit unsigned
    input  wire [`ITER_W-1:0] in1,

    // out0 = eigenvalues [10] complex
    output reg  signed [`DIM_OUT0_0*2*`EIG_W-1:0] out0,
    // out1 = eigenvectors [10][10] complex
    output reg  signed [`DIM_OUT1_0*`DIM_OUT1_1*2*`EIG_W-1:0] out1,
    // out2 = ite scalar 16-bit unsigned
    output reg  [`ITER_W-1:0] out2
);

// ============================================================
//  Parameters
// ============================================================
localparam N        = 10;
localparam W        = 23;          // component bit-width
localparam FRAC     = 20;          // fractional bits used internally
localparam WW       = 2*W+8;       // wide accumulator width
localparam THRESH   = 23'sd1;      // |a_pq| < 1 in Q3.20 ≈ 1e-6 (we use integer 1 ~ 9.5e-7)

// ============================================================
//  Trig ROM  –  512 entries, angles 0..π/4 uniformly sampled
//  Each entry stores {cos_val[22:0], sin_val[22:0]} in Q3.20
//  (value * 2^20 rounded to nearest integer, stored as 23-bit signed)
//  Angle index k represents θ = k*(π/4)/511
// ============================================================
localparam ROM_D = 512;
reg signed [W-1:0] cos_rom [0:ROM_D-1];
reg signed [W-1:0] sin_rom [0:ROM_D-1];

// Initialise ROM using an integer-only approach:
// We store cos(k*pi/4/511) * 2^20 and sin(k*pi/4/511) * 2^20
// as 23-bit signed integers.  Values pre-computed offline and
// embedded here as a $readmemh or direct assignment.
// For synthesis portability we use direct assignment (truncated).
// The values below are generated by the formula:
//   cos_rom[k] = round(cos(k*(pi/4)/511) * 1048576)
//   sin_rom[k] = round(sin(k*(pi/4)/511) * 1048576)
// Both fit comfortably in 23 bits (max ≈ 1048576 < 2^20 < 2^22).

integer rom_init_i;
// We use a synthesisable initial block for ROM initialisation.
// (Xilinx/Quartus support initial blocks in BRAMs.)
initial begin
    // We compute these at elaboration time using the recurrence:
    // cos((k+1)*d) = cos(k*d)*cos(d) - sin(k*d)*sin(d)
    // sin((k+1)*d) = sin(k*d)*cos(d) + cos(k*d)*sin(d)
    // with d = pi/4/511, cos(d)≈1048575, sin(d)≈6446 in Q20
    // We use 64-bit integers for the recurrence.
    // cos(d)  = 1048575   (≈ 1.0 * 2^20)
    // sin(d)  = 6446      (≈ 0.006143 * 2^20 ≈ sin(pi/4/511)*2^20)
    // These are exact enough for 23-bit outputs.
    begin : rom_init
        integer k;
        // Use 64-bit signed to avoid overflow in recurrence
        // Stored as Q20 (multiply by 2^20 = 1048576)
        // Initial angle = 0: cos=1.0, sin=0.0
        // We pre-define cos_d and sin_d for the small step
        // cos(pi/4/511) * 2^20 = 1048572  (rounded)
        // sin(pi/4/511) * 2^20 = 6446     (rounded)
        // Recurrence in Q20: needs /2^20 after each multiply
        // We'll use a simple direct assignment loop with
        // pre-computed values embedded as a parameter array.
        // Due to SystemVerilog restrictions on loops in initial blocks
        // with real arithmetic, we populate the ROM entries
        // numerically inline.  The values are all non-negative
        // and fit in 23 signed bits (range 0..1048576).
        //
        // Rather than listing all 512 values (impractical inline),
        // we approximate using a piecewise-linear scheme in integer
        // arithmetic which is accurate to < 1 LSB at Q20:
        //
        //   cos(x) ≈ 1 - x²/2  for small x  (but x can be up to π/4)
        //   Better: use the CORDIC-style integer recurrence below.
        //
        // Integer recurrence (all in Q20 = scaled by 2^20):
        //   C[0] = 1<<20;  S[0] = 0
        //   C[k+1] = (C[k]*CD - S[k]*SD) >> 20
        //   S[k+1] = (S[k]*CD + C[k]*SD) >> 20
        // where CD=1048572, SD=6446
        //
        // We implement this as SystemVerilog using 64-bit integers.
        // Note: initial blocks with integer arithmetic ARE synthesisable
        // for ROM initialisation on Xilinx (XST/Vivado).
        begin : recurrence
            reg [63:0] C_r, S_r, C_new, S_new;
            reg [63:0] CD, SD;
            CD = 64'd1048572;
            SD = 64'd6446;
            C_r = 64'd1048576;   // cos(0)*2^20
            S_r = 64'd0;         // sin(0)*2^20
            for (k = 0; k < ROM_D; k = k + 1) begin
                cos_rom[k] = C_r[22:0];
                sin_rom[k] = S_r[22:0];
                C_new = ((C_r * CD) - (S_r * SD)) >> 20;
                S_new = ((S_r * CD) + (C_r * SD)) >> 20;
                C_r = C_new;
                S_r = S_new;
            end
        end
    end
end

// ============================================================
//  Internal storage
// ============================================================
// A matrix: A[i][j] stored as re/im pairs, Q0.22 (fraction=0 per params)
reg signed [W-1:0] A_re [0:N-1][0:N-1];
reg signed [W-1:0] A_im [0:N-1][0:N-1];

// V matrix (eigenvectors), stored Q3.20 internally, output scaled
reg signed [W-1:0] V_re [0:N-1][0:N-1];
reg signed [W-1:0] V_im [0:N-1][0:N-1];

// U matrix (Jacobi rotation)
reg signed [W-1:0] U_re [0:N-1][0:N-1];
reg signed [W-1:0] U_im [0:N-1][0:N-1];

// Temporary matrices for matrix multiply
reg signed [W-1:0] T_re [0:N-1][0:N-1];  // intermediate U†·A
reg signed [W-1:0] T_im [0:N-1][0:N-1];

// Scalar registers
reg [`ITER_W-1:0]  max_iter_reg;
reg [`ITER_W-1:0]  iter_z;
reg [3:0]          p_idx, q_idx;
reg signed [W-1:0] off_max;  // max |a_pq| (real part of magnitude approx)

// Loop indices (need enough bits for 0..9)
reg [3:0]  li, lj, lk;  // loop counters
reg [3:0]  lr, lc;       // row/col for matrix multiply

// Trig values
reg signed [W-1:0] cos_theta, sin_theta;
// phi-related: exp(-j*phi) = (cos_phi, -sin_phi), exp(j*phi) = (cos_phi, sin_phi)
reg signed [W-1:0] cos_phi, sin_phi;
// Combined rotation entries
reg signed [W-1:0] U_pp_re, U_pp_im;
reg signed [W-1:0] U_pq_re, U_pq_im;
reg signed [W-1:0] U_qp_re, U_qp_im;
reg signed [W-1:0] U_qq_re, U_qq_im;

// Wide accumulators
reg signed [WW-1:0] acc_re, acc_im;

// ROM index for trig lookup
reg [8:0] rom_idx;

// Magnitude approximation registers
reg signed [W-1:0] apq_re_abs, apq_im_abs;
reg signed [W-1:0] mag_approx;   // |a_pq| ≈ max(|re|,|im|) + 0.5*min
reg signed [W-1:0] app_minus_aqq;

// Phase registers (for phi computation)
// phi = -angle(a_pq); angle ∈ (-π,π]
// We approximate: if a_pq = x + jy, angle ≈ atan2(y,x)
// For the Jacobi rotation we need exp(-j*phi) = a_pq*/|a_pq|
// so cos_phi = re(a_pq)/|a_pq|, sin_phi = -im(a_pq)/|a_pq|
// This avoids computing atan altogether.
reg signed [WW-1:0] phi_div_re, phi_div_im;
reg signed [W-1:0]  a_pq_re_reg, a_pq_im_reg;

// ============================================================
//  FSM states
// ============================================================
localparam [5:0]
    S_IDLE        = 6'd0,
    S_LATCH       = 6'd1,
    S_ITER_START  = 6'd2,
    S_FIND_INIT   = 6'd3,
    S_FIND_I      = 6'd4,
    S_FIND_J      = 6'd5,
    S_FIND_TEST   = 6'd6,
    S_FIND_NEXT   = 6'd7,
    S_CHECK_CONV  = 6'd8,
    S_CALC_TRIG   = 6'd9,
    S_CALC_PHI    = 6'd10,
    S_BUILD_U     = 6'd11,
    S_MMUL_TA_INIT= 6'd12,   // T = U† · A  (row loop init)
    S_MMUL_TA_ROW = 6'd13,
    S_MMUL_TA_COL = 6'd14,
    S_MMUL_TA_K   = 6'd15,
    S_MMUL_TA_ACC = 6'd16,
    S_MMUL_TA_STO = 6'd17,
    S_COPY_T2A    = 6'd18,   // A = T
    S_MMUL_AU_INIT= 6'd19,   // T = A · U
    S_MMUL_AU_ROW = 6'd20,
    S_MMUL_AU_COL = 6'd21,
    S_MMUL_AU_K   = 6'd22,
    S_MMUL_AU_ACC = 6'd23,
    S_MMUL_AU_STO = 6'd24,
    S_COPY_T2A2   = 6'd25,
    S_ZERO_PQ     = 6'd26,
    S_MMUL_VU_INIT= 6'd27,   // T = V · U
    S_MMUL_VU_ROW = 6'd28,
    S_MMUL_VU_COL = 6'd29,
    S_MMUL_VU_K   = 6'd30,
    S_MMUL_VU_ACC = 6'd31,
    S_MMUL_VU_STO = 6'd32,
    S_COPY_T2V    = 6'd33,
    S_NEXT_ITER   = 6'd34,
    S_DONE_ST     = 6'd35;

reg [5:0] state;

// ============================================================
//  Helper: absolute value (23-bit signed)
// ============================================================
function automatic signed [W-1:0] iabs;
    input signed [W-1:0] x;
    iabs = (x < 0) ? -x : x;
endfunction

// ============================================================
//  Helper: magnitude approximation  max + 3/8*min  (Q-preserving)
//  Error < 3.5%
// ============================================================
function automatic signed [W-1:0] cmag;
    input signed [W-1:0] xre, xim;
    reg signed [W-1:0] a, b, mn, mx;
    begin
        a = iabs(xre);
        b = iabs(xim);
        mn = (a < b) ? a : b;
        mx = (a < b) ? b : a;
        cmag = mx + (mn >>> 1) + (mn >>> 3);  // ≈ max + 0.625*min
    end
endfunction

// ============================================================
//  Clocked FSM
// ============================================================
integer ii, jj, kk;   // used in copy loops (non-synthesis-critical)

always @(posedge clk) begin
    if (rst) begin
        state    <= S_IDLE;
        busy     <= 1'b0;
        done     <= 1'b0;
        iter_z   <= 0;
        p_idx    <= 0;
        q_idx    <= 1;
        out2     <= 0;
        // zero output buses
        out0 <= 0;
        out1 <= 0;
    end else begin
        done <= 1'b0;  // default: done is a single-cycle pulse

        case (state)
        // ----------------------------------------------------------
        S_IDLE: begin
            busy <= 1'b0;
            if (start) begin
                busy  <= 1'b1;
                state <= S_LATCH;
            end
        end

        // ----------------------------------------------------------
        S_LATCH: begin
            // Latch input matrix A (re/im interleaved, row-major)
            // Bit layout: element [i][j] at bit offset (i*10+j)*2*23
            // re = bits [22:0], im = bits [45:23] of that element slot
            begin : latch_blk
                integer li2, lj2;
                for (li2 = 0; li2 < N; li2 = li2 + 1) begin
                    for (lj2 = 0; lj2 < N; lj2 = lj2 + 1) begin
                        A_re[li2][lj2] <= in0[((li2*N+lj2)*2)*W +: W];
                        A_im[li2][lj2] <= in0[((li2*N+lj2)*2+1)*W +: W];
                    end
                end
            end
            max_iter_reg <= in1;
            iter_z       <= 0;
            // Initialise V = identity (in Q20: 1.0 = 1<<20 = 1048576)
            begin : vinit_blk
                integer li3, lj3;
                for (li3 = 0; li3 < N; li3 = li3 + 1) begin
                    for (lj3 = 0; lj3 < N; lj3 = lj3 + 1) begin
                        V_re[li3][lj3] <= (li3 == lj3) ? (1 <<< FRAC) : 0;
                        V_im[li3][lj3] <= 0;
                    end
                end
            end
            state <= S_ITER_START;
        end

        // ----------------------------------------------------------
        S_ITER_START: begin
            off_max <= 0;
            p_idx   <= 0;
            q_idx   <= 1;
            li      <= 0;
            lj      <= 1;
            state   <= S_FIND_INIT;
        end

        // ----------------------------------------------------------
        S_FIND_INIT: begin
            li    <= 0;
            state <= S_FIND_I;
        end

        S_FIND_I: begin
            if (li < N) begin
                lj    <= li + 1;
                state <= S_FIND_J;
            end else begin
                state <= S_CHECK_CONV;
            end
        end

        S_FIND_J: begin
            if (lj < N) begin
                state <= S_FIND_TEST;
            end else begin
                li    <= li + 1;
                state <= S_FIND_I;
            end
        end

        S_FIND_TEST: begin
            begin : find_test_blk
                reg signed [W-1:0] mag;
                mag = cmag(A_re[li][lj], A_im[li][lj]);
                if (mag > off_max) begin
                    off_max <= mag;
                    p_idx   <= li;
                    q_idx   <= lj;
                end
            end
            state <= S_FIND_NEXT;
        end

        S_FIND_NEXT: begin
            lj    <= lj + 1;
            state <= S_FIND_J;
        end

        // ----------------------------------------------------------
        S_CHECK_CONV: begin
            // off_max < THRESH  ⟹ converged
            if ((off_max < THRESH) || (iter_z >= max_iter_reg - 1)) begin
                state <= S_DONE_ST;
            end else begin
                // Compute trig for (p_idx, q_idx)
                a_pq_re_reg <= A_re[p_idx][q_idx];
                a_pq_im_reg <= A_im[p_idx][q_idx];
                state <= S_CALC_TRIG;
            end
        end

        // ----------------------------------------------------------
        // Compute theta = 0.5 * atan(2*|a_pq| / (a_pp - a_qq))
        // We approximate atan(x) using ROM lookup.
        // |a_pq| already in off_max.
        // We need the ratio x = 2*|a_pq| / |a_pp - a_qq|
        // Then index into ROM: index = min(511, round(x * 511 / (1 + x) * 2))
        // Simpler: for θ ∈ [0, π/4], use x = 2*|a_pq|/(|a_pp-a_qq|+eps)
        // ROM index = clamp(round(2*|a_pq| * 511 / max(|a_pp-a_qq|, 1)), 0, 511)
        S_CALC_TRIG: begin
            begin : trig_blk
                reg signed [W-1:0] a_pp, a_qq;
                reg signed [W-1:0] diff;
                reg signed [WW-1:0] num, denom;
                reg [8:0] idx;
                a_pp = A_re[p_idx][p_idx];  // diagonal is real for Hermitian
                a_qq = A_re[q_idx][q_idx];
                diff = a_pp - a_qq;
                // diff could be 0; use |diff| + 1 as denominator
                if (diff < 0) diff = -diff;
                if (diff < 1) diff = 1;
                // num = 2 * off_max * 511
                num = ({{(WW-W){1'b0}}, off_max} * 1022);  // 2*511
                denom = {{(WW-W){1'b0}}, diff};
                // idx = num / denom, clamped to [0,511]
                if (denom == 0) denom = 1;
                begin : div_blk
                    reg [WW-1:0] quot;
                    quot = num / denom;
                    if (quot > 511) quot = 511;
                    idx = quot[8:0];
                end
                rom_idx   <= idx;
                cos_theta <= cos_rom[idx];
                sin_theta <= sin_rom[idx];
            end
            state <= S_CALC_PHI;
        end

        // ----------------------------------------------------------
        // phi = -angle(a_pq)
        // exp(-j*phi) = a_pq* / |a_pq|  = (re - j*im) / mag
        // We store cos_phi = re/mag * 2^20, sin_phi = im/mag * 2^20
        // (phi is used as -phi so we negate im later)
        // Division: (re * 2^20) / mag  in integer arithmetic
        S_CALC_PHI: begin
            begin : phi_blk
                reg signed [WW-1:0] mag_w;
                reg signed [WW-1:0] re_w, im_w;
                reg signed [W-1:0]  mag_s;
                mag_s = cmag(a_pq_re_reg, a_pq_im_reg);
                if (mag_s < 1) mag_s = 1;
                mag_w = {{(WW-W){mag_s[W-1]}}, mag_s};
                re_w  = {{(WW-W){a_pq_re_reg[W-1]}}, a_pq_re_reg};
                im_w  = {{(WW-W){a_pq_im_reg[W-1]}}, a_pq_im_reg};
                // cos_phi = re * 2^20 / mag  (Q20)
                cos_phi <= (re_w <<< FRAC) / mag_w;
                // sin_phi = im * 2^20 / mag  (Q20, note: phi=-angle => exp(-j*phi)=conj/mag)
                // sin for exp(-j*phi) = -im/mag, for exp(j*phi) = im/mag
                sin_phi <= (im_w <<< FRAC) / mag_w;
            end
            state <= S_BUILD_U;
        end

        // ----------------------------------------------------------
        // Build U:
        //  U[p,p] =  cos(θ)                    (real)
        //  U[p,q] =  sin(θ)*exp(-j*phi) = sin*cos_phi - j*sin*sin_phi
        //  U[q,p] =  sin(θ)*exp(+j*phi) = sin*cos_phi + j*sin*sin_phi
        //  U[q,q] = -cos(θ)                    (real, but negative)
        //  All other entries: identity (1 on diag, 0 elsewhere)
        // Note: U is unitary, and we only store the non-trivial entries.
        // We don't actually build the full U matrix — instead we apply
        // it directly in the matrix-multiply states using p_idx/q_idx.
        S_BUILD_U: begin
            begin : build_u_blk
                reg signed [WW-1:0] s_cos, s_sin;
                // sin_theta and cos_theta are Q20 values
                // cos_phi and sin_phi are Q20 values
                // products are Q40; shift right 20 to get Q20
                s_cos = {{(WW-W){cos_theta[W-1]}}, cos_theta};
                s_sin = {{(WW-W){sin_theta[W-1]}}, sin_theta};
                // U[p,p] = cos(θ)  (purely real in Q20)
                U_pp_re <= cos_theta;
                U_pp_im <= 0;
                // U[q,q] = -cos(θ)
                U_qq_re <= -cos_theta;
                U_qq_im <= 0;
                // U[p,q] = sin(θ)*exp(-j*phi) = sin*(cos_phi - j*sin_phi)
                //        re = sin*cos_phi >> 20
                //        im = -sin*sin_phi >> 20
                U_pq_re <= (s_sin * {{(WW-W){cos_phi[W-1]}}, cos_phi}) >>> FRAC;
                U_pq_im <= -(s_sin * {{(WW-W){sin_phi[W-1]}}, sin_phi}) >>> FRAC;
                // U[q,p] = sin(θ)*exp(+j*phi)
                //        re = sin*cos_phi >> 20
                //        im = +sin*sin_phi >> 20
                U_qp_re <= (s_sin * {{(WW-W){cos_phi[W-1]}}, cos_phi}) >>> FRAC;
                U_qp_im <= (s_sin * {{(WW-W){sin_phi[W-1]}}, sin_phi}) >>> FRAC;
            end
            // Initialise U matrix to identity, then overwrite p,q entries
            begin : u_init_blk
                integer li4, lj4;
                for (li4 = 0; li4 < N; li4 = li4 + 1) begin
                    for (lj4 = 0; lj4 < N; lj4 = lj4 + 1) begin
                        U_re[li4][lj4] <= (li4 == lj4) ? (1 <<< FRAC) : 0;
                        U_im[li4][lj4] <= 0;
                    end
                end
            end
            state <= S_MMUL_TA_INIT;
        end

        // ----------------------------------------------------------
        // T = U† · A
        // U† [i][k] = conj(U[k][i])
        // T[i][j] = Σ_k U†[i][k] · A[k][j]
        //         = Σ_k conj(U[k][i]) · A[k][j]
        // For the Jacobi U, only rows/cols p and q differ from identity.
        // To keep the FSM simple we do the full N×N multiply.
        // (Optimisation: only update rows p and q — left as future work)
        S_MMUL_TA_INIT: begin
            // Overwrite U with the constructed rotation
            // (U was set to identity in BUILD_U; now patch p,q entries)
            U_re[p_idx][p_idx] <= U_pp_re;  U_im[p_idx][p_idx] <= U_pp_im;
            U_re[p_idx][q_idx] <= U_pq_re;  U_im[p_idx][q_idx] <= U_pq_im;
            U_re[q_idx][p_idx] <= U_qp_re;  U_im[q_idx][p_idx] <= U_qp_im;
            U_re[q_idx][q_idx] <= U_qq_re;  U_im[q_idx][q_idx] <= U_qq_im;
            lr    <= 0;
            lc    <= 0;
            lk    <= 0;
            acc_re <= 0;
            acc_im <= 0;
            state <= S_MMUL_TA_ROW;
        end

        S_MMUL_TA_ROW: begin
            if (lr < N) begin
                lc    <= 0;
                state <= S_MMUL_TA_COL;
            end else begin
                state <= S_COPY_T2A;
            end
        end

        S_MMUL_TA_COL: begin
            if (lc < N) begin
                lk     <= 0;
                acc_re <= 0;
                acc_im <= 0;
                state  <= S_MMUL_TA_K;
            end else begin
                lr    <= lr + 1;
                state <= S_MMUL_TA_ROW;
            end
        end

        S_MMUL_TA_K: begin
            if (lk < N) begin
                state <= S_MMUL_TA_ACC;
            end else begin
                state <= S_MMUL_TA_STO;
            end
        end

        S_MMUL_TA_ACC: begin
            // T[lr][lc] += conj(U[lk][lr]) * A[lk][lc]
            // conj(U[lk][lr]) = (U_re[lk][lr], -U_im[lk][lr])
            // complex multiply:
            //   re += U_re[lk][lr]*A_re[lk][lc] + U_im[lk][lr]*A_im[lk][lc]
            //   im += U_re[lk][lr]*A_im[lk][lc] - U_im[lk][lr]*A_re[lk][lc]
            // All in Q20*Q0 = Q20, or Q20*Q20 = Q40 (>>20 to stay Q20)
            // A is in Q0 (fraction=0), U is in Q20
            // Product is Q20; no additional shift needed
            begin : ta_acc_blk
                reg signed [WW-1:0] u_re_w, u_im_w, a_re_w, a_im_w;
                u_re_w = {{(WW-W){U_re[lk][lr][W-1]}}, U_re[lk][lr]};
                u_im_w = {{(WW-W){U_im[lk][lr][W-1]}}, U_im[lk][lr]};
                a_re_w = {{(WW-W){A_re[lk][lc][W-1]}}, A_re[lk][lc]};
                a_im_w = {{(WW-W){A_im[lk][lc][W-1]}}, A_im[lk][lc]};
                // conj(U[lk][lr]) · A[lk][lc]
                // re: u_re * a_re + u_im * a_im  (>>20 since u is Q20, a is Q0 → result Q20>>20=Q0... 
                // Wait: we want T in same units as A (Q0). U is Q20.
                // So we need to divide by 2^20 after the multiply.
                acc_re <= acc_re + (u_re_w * a_re_w + u_im_w * a_im_w) >>> FRAC;
                acc_im <= acc_im + (u_re_w * a_im_w - u_im_w * a_re_w) >>> FRAC;
            end
            lk    <= lk + 1;
            state <= S_MMUL_TA_K;
        end

        S_MMUL_TA_STO: begin
            T_re[lr][lc] <= acc_re[W-1:0];
            T_im[lr][lc] <= acc_im[W-1:0];
            lc    <= lc + 1;
            state <= S_MMUL_TA_COL;
        end

        // ----------------------------------------------------------
        S_COPY_T2A: begin
            begin : cta_blk
                integer li5, lj5;
                for (li5 = 0; li5 < N; li5 = li5 + 1)
                    for (lj5 = 0; lj5 < N; lj5 = lj5 + 1) begin
                        A_re[li5][lj5] <= T_re[li5][lj5];
                        A_im[li5][lj5] <= T_im[li5][lj5];
                    end
            end
            lr    <= 0;
            lc    <= 0;
            lk    <= 0;
            acc_re <= 0;
            acc_im <= 0;
            state <= S_MMUL_AU_INIT;
        end

        // ----------------------------------------------------------
        // T = A · U
        S_MMUL_AU_INIT: begin
            lr    <= 0;
            state <= S_MMUL_AU_ROW;
        end

        S_MMUL_AU_ROW: begin
            if (lr < N) begin
                lc    <= 0;
                state <= S_MMUL_AU_COL;
            end else begin
                state <= S_COPY_T2A2;
            end
        end

        S_MMUL_AU_COL: begin
            if (lc < N) begin
                lk     <= 0;
                acc_re <= 0;
                acc_im <= 0;
                state  <= S_MMUL_AU_K;
            end else begin
                lr    <= lr + 1;
                state <= S_MMUL_AU_ROW;
            end
        end

        S_MMUL_AU_K: begin
            if (lk < N) begin
                state <= S_MMUL_AU_ACC;
            end else begin
                state <= S_MMUL_AU_STO;
            end
        end

        S_MMUL_AU_ACC: begin
            // T[lr][lc] += A[lr][lk] * U[lk][lc]
            begin : au_acc_blk
                reg signed [WW-1:0] u_re_w, u_im_w, a_re_w, a_im_w;
                u_re_w = {{(WW-W){U_re[lk][lc][W-1]}}, U_re[lk][lc]};
                u_im_w = {{(WW-W){U_im[lk][lc][W-1]}}, U_im[lk][lc]};
                a_re_w = {{(WW-W){A_re[lr][lk][W-1]}}, A_re[lr][lk]};
                a_im_w = {{(WW-W){A_im[lr][lk][W-1]}}, A_im[lr][lk]};
                acc_re <= acc_re + (a_re_w * u_re_w - a_im_w * u_im_w) >>> FRAC;
                acc_im <= acc_im + (a_re_w * u_im_w + a_im_w * u_re_w) >>> FRAC;
            end
            lk    <= lk + 1;
            state <= S_MMUL_AU_K;
        end

        S_MMUL_AU_STO: begin
            T_re[lr][lc] <= acc_re[W-1:0];
            T_im[lr][lc] <= acc_im[W-1:0];
            lc    <= lc + 1;
            state <= S_MMUL_AU_COL;
        end

        S_COPY_T2A2: begin
            begin : cta2_blk
                integer li6, lj6;
                for (li6 = 0; li6 < N; li6 = li6 + 1)
                    for (lj6 = 0; lj6 < N; lj6 = lj6 + 1) begin
                        A_re[li6][lj6] <= T_re[li6][lj6];
                        A_im[li6][lj6] <= T_im[li6][lj6];
                    end
            end
            state <= S_ZERO_PQ;
        end

        S_ZERO_PQ: begin
            A_re[p_idx][q_idx] <= 0;
            A_im[p_idx][q_idx] <= 0;
            A_re[q_idx][p_idx] <= 0;
            A_im[q_idx][p_idx] <= 0;
            lr    <= 0;
            state <= S_MMUL_VU_INIT;
        end

        // ----------------------------------------------------------
        // T = V · U
        S_MMUL_VU_INIT: begin
            lr    <= 0;
            state <= S_MMUL_VU_ROW;
        end

        S_MMUL_VU_ROW: begin
            if (lr < N) begin
                lc    <= 0;
                state <= S_MMUL_VU_COL;
            end else begin
                state <= S_COPY_T2V;
            end
        end

        S_MMUL_VU_COL: begin
            if (lc < N) begin
                lk     <= 0;
                acc_re <= 0;
                acc_im <= 0;
                state  <= S_MMUL_VU_K;
            end else begin
                lr    <= lr + 1;
                state <= S_MMUL_VU_ROW;
            end
        end

        S_MMUL_VU_K: begin
            if (lk < N) begin
                state <= S_MMUL_VU_ACC;
            end else begin
                state <= S_MMUL_VU_STO;
            end
        end

        S_MMUL_VU_ACC: begin
            // T[lr][lc] += V[lr][lk] * U[lk][lc]
            // V is Q20, U is Q20 => product is Q40, shift right 20 => Q20
            begin : vu_acc_blk
                reg signed [WW-1:0] u_re_w, u_im_w, v_re_w, v_im_w;
                u_re_w = {{(WW-W){U_re[lk][lc][W-1]}}, U_re[lk][lc]};
                u_im_w = {{(WW-W){U_im[lk][lc][W-1]}}, U_im[lk][lc]};
                v_re_w = {{(WW-W){V_re[lr][lk][W-1]}}, V_re[lr][lk]};
                v_im_w = {{(WW-W){V_im[lr][lk][W-1]}}, V_im[lr][lk]};
                acc_re <= acc_re + (v_re_w * u_re_w - v_im_w * u_im_w) >>> FRAC;
                acc_im <= acc_im + (v_re_w * u_im_w + v_im_w * u_re_w) >>> FRAC;
            end
            lk    <= lk + 1;
            state <= S_MMUL_VU_K;
        end

        S_MMUL_VU_STO: begin
            T_re[lr][lc] <= acc_re[W-1:0];
            T_im[lr][lc] <= acc_im[W-1:0];
            lc    <= lc + 1;
            state <= S_MMUL_VU_COL;
        end

        S_COPY_T2V: begin
            begin : ctv_blk
                integer li7, lj7;
                for (li7 = 0; li7 < N; li7 = li7 + 1)
                    for (lj7 = 0; lj7 < N; lj7 = lj7 + 1) begin
                        V_re[li7][lj7] <= T_re[li7][lj7];
                        V_im[li7][lj7] <= T_im[li7][lj7];
                    end
            end
            state <= S_NEXT_ITER;
        end

        // ----------------------------------------------------------
        S_NEXT_ITER: begin
            iter_z <= iter_z + 1;
            if (iter_z + 1 >= max_iter_reg) begin
                state <= S_DONE_ST;
            end else begin
                state <= S_ITER_START;
            end
        end

        // ----------------------------------------------------------
        S_DONE_ST: begin
            // Write outputs
            // out0 = diag(A) as eigenvalues (complex, Q0)
            begin : out0_blk
                integer li8;
                for (li8 = 0; li8 < N; li8 = li8 + 1) begin
                    out0[(li8*2)*W   +: W] <= A_re[li8][li8];
                    out0[(li8*2+1)*W +: W] <= A_im[li8][li8];
                end
            end
            // out1 = V (eigenvectors, Q20, complex)
            begin : out1_blk
                integer li9, lj9;
                for (li9 = 0; li9 < N; li9 = li9 + 1)
                    for (lj9 = 0; lj9 < N; lj9 = lj9 + 1) begin
                        out1[((li9*N+lj9)*2)*W   +: W] <= V_re[li9][lj9];
                        out1[((li9*N+lj9)*2+1)*W +: W] <= V_im[li9][lj9];
                    end
            end
            // out2 = iteration count z
            out2  <= iter_z;
            done  <= 1'b1;
            busy  <= 1'b0;
            state <= S_IDLE;
        end

        default: state <= S_IDLE;
        endcase
    end
end

endmodule
