## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk100]
set_property IOSTANDARD LVCMOS33 [get_ports clk100]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk100]

## VGA Connector
set_property PACKAGE_PIN G19 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN H19 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN N19 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN N18 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN L18 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN J17 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN H17 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN D17 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN P19 [get_ports vga_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property PACKAGE_PIN R19 [get_ports vga_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]

## LEDs
set_property PACKAGE_PIN U16 [get_ports config_finished_l]
set_property IOSTANDARD LVCMOS33 [get_ports config_finished_l]
set_property PACKAGE_PIN E19 [get_ports config_finished_r]
set_property IOSTANDARD LVCMOS33 [get_ports config_finished_r]

## Buttons
set_property PACKAGE_PIN U18 [get_ports btnc]
set_property IOSTANDARD LVCMOS33 [get_ports btnc]
set_property PACKAGE_PIN W19 [get_ports btnl]
set_property IOSTANDARD LVCMOS33 [get_ports btnl]
set_property PACKAGE_PIN T17 [get_ports btnr]
set_property IOSTANDARD LVCMOS33 [get_ports btnr]

## Left Camera - Pmod JB
set_property PACKAGE_PIN A14 [get_ports ov7670_pwdn_l]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pwdn_l]
set_property PACKAGE_PIN A16 [get_ports {ov7670_data_l[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_l[0]}]
set_property PACKAGE_PIN B15 [get_ports {ov7670_data_l[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_l[2]}]
set_property PACKAGE_PIN B16 [get_ports {ov7670_data_l[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_l[4]}]
set_property PACKAGE_PIN A15 [get_ports ov7670_reset_l]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_reset_l]
set_property PACKAGE_PIN A17 [get_ports {ov7670_data_l[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_l[1]}]
set_property PACKAGE_PIN C15 [get_ports {ov7670_data_l[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_l[3]}]
set_property PACKAGE_PIN C16 [get_ports {ov7670_data_l[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_l[5]}]

## Left Camera - Pmod JC
set_property PACKAGE_PIN K17 [get_ports {ov7670_data_l[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_l[6]}]
set_property PACKAGE_PIN M18 [get_ports ov7670_xclk_l]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_xclk_l]
set_property PACKAGE_PIN N17 [get_ports ov7670_href_l]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_href_l]
set_property PACKAGE_PIN P18 [get_ports ov7670_siod_l]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_siod_l]
set_property PULLUP TRUE [get_ports ov7670_siod_l]
set_property PACKAGE_PIN L17 [get_ports {ov7670_data_l[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_l[7]}]
set_property PACKAGE_PIN M19 [get_ports ov7670_pclk_l]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pclk_l]
create_clock -name ov7670_pclk_l_pin -period 40.00 [get_ports ov7670_pclk_l]
set_property PACKAGE_PIN P17 [get_ports ov7670_vsync_l]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_vsync_l]
set_property PACKAGE_PIN R18 [get_ports ov7670_sioc_l]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_sioc_l]

## Right Camera - Pmod JA
set_property PACKAGE_PIN J1 [get_ports {ov7670_data_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_r[6]}]
set_property PACKAGE_PIN L2 [get_ports ov7670_xclk_r]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_xclk_r]
set_property PACKAGE_PIN J2 [get_ports ov7670_href_r]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_href_r]
set_property PACKAGE_PIN G2 [get_ports ov7670_siod_r]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_siod_r]
set_property PULLUP TRUE [get_ports ov7670_siod_r]
set_property PACKAGE_PIN H1 [get_ports {ov7670_data_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_r[7]}]
set_property PACKAGE_PIN K2 [get_ports ov7670_pclk_r]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pclk_r]
create_clock -name ov7670_pclk_r_pin -period 40.00 [get_ports ov7670_pclk_r]
set_property PACKAGE_PIN H2 [get_ports ov7670_vsync_r]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_vsync_r]
set_property PACKAGE_PIN G3 [get_ports ov7670_sioc_r]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_sioc_r]

## Right Camera - Pmod JXADC
set_property PACKAGE_PIN J3 [get_ports ov7670_pwdn_r]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pwdn_r]
set_property PACKAGE_PIN L3 [get_ports {ov7670_data_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_r[0]}]
set_property PACKAGE_PIN M2 [get_ports {ov7670_data_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_r[2]}]
set_property PACKAGE_PIN N2 [get_ports {ov7670_data_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_r[4]}]
set_property PACKAGE_PIN K3 [get_ports ov7670_reset_r]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_reset_r]
set_property PACKAGE_PIN M3 [get_ports {ov7670_data_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_r[1]}]
set_property PACKAGE_PIN M1 [get_ports {ov7670_data_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_r[3]}]
set_property PACKAGE_PIN N1 [get_ports {ov7670_data_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_r[5]}]

## Clock domain crossings
set_clock_groups -asynchronous \
  -group [get_clocks sys_clk_pin] \
  -group [get_clocks ov7670_pclk_l_pin] \
  -group [get_clocks ov7670_pclk_r_pin]
