"""read_report tool: surgical reads of generated reports + sim logs."""

from __future__ import annotations

from pathlib import Path
from typing import Any

MAX_LINES = 400

KNOWN_REPORTS = {
    "sim_log": "sim/xsim.log",
    "sim_summary": "sim/sim_summary.json",
    "vivado_synth_log": "reports/vivado_synth.log",
    "vivado_impl_log": "reports/vivado_impl.log",
    "timing_synth": "reports/timing_synth.rpt",
    "timing_impl": "reports/timing_impl.rpt",
    "util_synth": "reports/util_synth.rpt",
    "util_impl": "reports/util_impl.rpt",
    "pnr_synth_summary": "reports/pnr_summary_synth.json",
    "pnr_impl_summary": "reports/pnr_summary_impl.json",
    "build_tcl": "build.tcl",
    "timing_xdc": "constraints/timing.xdc",
}


def build_read_report_tool(ctx):
    from . import Tool

    schema = {
        "name": "read_report",
        "description": (
            "Read a section of a known report or log generated by run_sim/run_pnr. "
            f"Names: {', '.join(KNOWN_REPORTS)}. Optionally pass `grep` to filter "
            "lines, and `max_lines` to bound output (default 400)."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "enum": list(KNOWN_REPORTS.keys()),
                },
                "grep": {
                    "type": "string",
                    "description": "Substring to filter lines (case-insensitive)",
                },
                "max_lines": {
                    "type": "integer",
                    "description": "Max lines returned (default 400, hard cap 800)",
                },
                "tail": {
                    "type": "boolean",
                    "description": "Return the last max_lines lines instead of the head",
                },
            },
            "required": ["name"],
        },
    }

    def handler(args: dict) -> Any:
        name = args.get("name")
        if name not in KNOWN_REPORTS:
            return {"error": f"unknown report: {name}"}
        path = ctx.build_dir / KNOWN_REPORTS[name]
        if not path.exists():
            return {"error": f"report not found: {KNOWN_REPORTS[name]}"}
        text = path.read_text(errors="replace")
        lines = text.splitlines()
        grep = args.get("grep")
        if grep:
            g = grep.lower()
            lines = [ln for ln in lines if g in ln.lower()]
        cap = min(int(args.get("max_lines", MAX_LINES)), 800)
        tail = bool(args.get("tail"))
        selected = lines[-cap:] if tail else lines[:cap]
        return {
            "name": name,
            "path": str(path.relative_to(ctx.build_dir)),
            "total_lines": len(lines),
            "returned_lines": len(selected),
            "tail": tail,
            "content": "\n".join(selected),
        }

    return Tool(schema=schema, handler=handler)
